#ifndef PYTHONIC_INCLUDE_BUILTIN_PENDINGDEPRECATIONWARNING_HPP
#define PYTHONIC_INCLUDE_BUILTIN_PENDINGDEPRECATIONWARNING_HPP

#include "pythonic/include/types/exceptions.hpp"

PYTHONIC_NS_BEGIN

namespace __builtin__
{

  PYTHONIC_EXCEPTION_DECL(PendingDeprecationWarning)
}
PYTHONIC_NS_END

#endif
