#runas solve(2, 100)
#pythran export solve(int, int)
'''
How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100
'''

def solve(start, end):
 terms = {}
 count = 0
 for a in xrange(start, end + 1):
     for b in xrange(start, end + 1):
         c = pow(long(a),b)
         if not terms.get(c, 0):
             terms[c] = 1
             count = count + 1

 return count
