#pythran export solve()
'''
How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100
'''

def solve():
 terms = {}
 count = 0
 for a in xrange(2,101):
     for b in xrange(2,101):
         c = pow(a,b)
         if not terms.get(c, 0):
             terms[c] = 1
             count = count + 1

 return count
