#!/usr/bin/env python
import argparse
from pythran import toolchain as tc
import sys

parser = argparse.ArgumentParser(prog='pythran-config',
                                 description='output build options for pythran-generated code',
                                 epilog="It's a megablast!"
                                 )

parser.add_argument('--cflags', action='store_true', 
                    help='print compilation flags')

parser.add_argument('--libs', action='store_true',
                    help='print linker flags')

args = parser.parse_args(sys.argv[1:])

if args.cflags:
    print ' '.join(tc.cppflags() + tc.cxxflags())

if args.libs:
    print ' '.join(tc.ldflags())

# what a great editor!
# vim: ft=python
