#!/usr/bin/env python
import argparse
import distutils.sysconfig
import numpy
import os
import sys

from pythran.config import make_extension

parser = argparse.ArgumentParser(
    prog='pythran-config',
    description='output build options for pythran-generated code',
    epilog="It's a megablast!"
    )

parser.add_argument('--compiler', action='store_true',
                    help='print default compiler')

parser.add_argument('--cflags', action='store_true',
                    help='print compilation flags')

parser.add_argument('--libs', action='store_true',
                    help='print linker flags')

args = parser.parse_args(sys.argv[1:])

output = []

extension = make_extension()

if args.compiler:
    output.append(os.environ.get('CXX', 'c++'))

if args.cflags:
    def fmt_define(define):
        name, value = define
        if value is None:
            return '-D' + name
        else:
            return '-D' + name + '=' + value
    output.extend(fmt_define(define) for define in extension['define_macros'])
    output.extend(('-I' + include) for include in extension['include_dirs'])
    output.append('-I' + numpy.get_include())
    output.append('-I' + distutils.sysconfig.get_python_inc())

if args.libs:
    output.extend(('-L' + include) for include in extension['library_dirs'])
    output.append('-L' + distutils.sysconfig.get_config_var('LIBPL'))
    output.extend(('-l' + include) for include in extension['libraries'])
    output.extend(distutils.sysconfig.get_config_var('LIBS').split())
    output.append('-lpython' + distutils.sysconfig.get_config_var('VERSION'))

if output:
    print ' '.join(output)

# what a great editor!
# vim: ft=python
