import unittest
import pythran
import pep8
import glob
import os


class TestPEP8(unittest.TestCase):
    '''
    Enable automatic pep8 compliance testing

    Every module in the pythran package is scanned for pep8 errors
    '''
    pass


def generic_test_package(self, mod_file):
    chk = pep8.Checker(mod_file)
    chk.report._ignore_code = lambda s: s in ('E121', 'E122', 'E123', 'E124',
                                              'E125', 'E126', 'E127', 'E128',
                                              'E129')
    failed = chk.check_all()
    self.assertEqual(failed, 0)

# Get Pythran install path from import
path = os.path.dirname(pythran.__file__)

# Check all py
files = glob.glob(os.path.join(path, "*.py"))

# Exclude autogenerated file
try: files.remove(os.path.join(path, "parsetab.py"))
except ValueError:pass

# Needed to capture modfile
def method_generator(modfile):
    return lambda self: generic_test_package(self, modfile)

# Add the "magic" test method that fit unittest framework
for modfile in files:
    module_name, _ = os.path.splitext(os.path.basename(modfile))
    setattr(TestPEP8, 'test_' + module_name, method_generator(modfile))
