name: asan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v6
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
    - name: Install dependencies
      run: |
        pip install scipy-openblas64
        pip install pytest-xdist
        sudo apt install ${{ matrix.cpp-version }}
        sudo apt install libopenblas-dev  # for meson integration testing
    - name: Setup
      run: |
        python -m pip install .
        python -m pip install . 'pythran[build]'
        python -m pip install . 'pythran[test]'
        printf '[compiler]\nblas=scipy-openblas\n' > ~/.config/.pythranrc
        printf 'cflags=-std=c++17 -O1 -fsanitize=address\n' >> ~/.config/.pythranrc
        printf 'ldflags=-fsanitize=address\n' >> ~/.config/.pythranrc
    - name: Testing
      run: |
        echo 'void foo() {}' | gcc -x c -fPIC -shared -fsanitize=address -
        ASAN_OPTIONS=detect_leaks=0 LD_PRELOAD=`ldd a.out | grep libasan.so | awk '{print $3}'` pytest pythran/tests/test_cases.py pythran/tests/test_scipy.py -v -x --numprocesses=auto
