name: doc

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10"]
        cpp-version: [g++-8, clang-6.0]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scipy
        pip install pytest-xdist
        sudo apt install libopenblas-dev ${{ matrix.cpp-version }}
    - name: Setup
      run: |
        python -m pip install .
        python -m pip install . 'pythran[test]'
        printf '[commpiler]\nblas=openblas\n' > ~/.pythranrc
    - name: Testing documentation
      run: |
        export CC=`echo ${{ matrix.cpp-version }} | sed -e 's/g++/gcc/'`
        export CXX=`echo ${{ matrix.cpp-version }} | sed -e 's/clang/clang++/'`
        pytest pythran/tests/notebooks docs/examples --nbval
