name: no-setuptools

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scipy-openblas64
    - name: Setup
      run: |
        python -m pip install .
        python -m pip uninstall -y setuptools  # the goal of that check is to test codegen without setuptools
    - name: Testing pythran-config
      run: |
        pythran-config --cflags-pythran-only
    - name: Testing scipy
      run: |
        find pythran/tests/scipy/ -name '*.py' -exec pythran -E {} \;
